import "./global.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body>

        <header>
          <p>HEADER</p>
        </header>

        {children}

        <footer>
          <p>FOOTER</p>
        </footer>
        
      </body>
    </html>
  )
}
